### ISSUE TITLE
Missing Example Usage

### ISSUE THREAD

**Issue by tyleratopploans** [athos/lein-with-env-vars#1]
My team just followed your README and didn't see the variable set as expected. Could you link us to some example projects using this, or provide in this repo?

**Comment by athos** [comment]
Sure. I will add some example code later.

**Comment by athos** [comment]
@tyleratopploans Hey, I just added [the example project](https://github.com/athos/lein-with-env-vars/tree/master/examples/example) to demostrate how to use the plugin. I hope this helps 😉

**Comment by tyleratopploans** [comment]
@athos, thanks! That's exactly what I was looking for. :)
